# Generated by Django 2.2.8 on 2019-12-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191218_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_picture',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/%h/%m'),
        ),
    ]
