# Generated by Django 2.2.8 on 2019-12-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191219_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_picture',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
